name: docker

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to HSDP Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.na1.hsdp.io
          username: ${{ secrets.HSDP_DOCKER_USERNAME }}
          password: ${{ secrets.HSDP_DOCKER_PASSWORD }}
      - uses: actions/checkout@v5
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.na1.hsdp.io/alcon-dhs-docker-registry/kong-plugin-mtlsauth
